//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAxos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AxosnetEntities : DbContext
    {
        public AxosnetEntities()
            : base("name=AxosnetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catCurrencies> catCurrencies { get; set; }
        public virtual DbSet<catSuppliers> catSuppliers { get; set; }
        public virtual DbSet<tblReceipts> tblReceipts { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    }
}
