//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAxos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceipts
    {
        public int receiptId { get; set; }
        public int supplierId { get; set; }
        public decimal amount { get; set; }
        public int currencyId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string comment { get; set; }
    
        public virtual catCurrencies catCurrencies { get; set; }
        public virtual catSuppliers catSuppliers { get; set; }
    }
}
